name: Feature request
description: Suggest an idea to enhance Safe Execute
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature for **Safe Execute**!
  - type: markdown
    attributes:
      value: |
        Before filing a new issue, **please do a quick search** to ensure this feature hasn't already been requested. You can do this by going to [this link](https://github.com/rahulc0dy/safe-execute/issues) and typing keywords related to your request.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of the problem you're facing with Safe Execute. **Example:** "I'm always frustrated when my function errors are not handled gracefully..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. **Example:** "I would like Safe Execute to allow configuration of custom error messages and logging..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered. **Example:** "I have considered using try/catch wrappers manually, but it becomes repetitive..."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by dragging files into this area.
    validations:
      required: false
