name: Bug report
description: Create a report to help us improve Safe Execute
title: "[BUG]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in the **Safe Execute** project!
  - type: markdown
    attributes:
      value: |
        Before filing a new issue, please do a quick search to ensure this bug hasn't already been reported. You can check existing issues [here](https://github.com/rahulc0dy/safe-execute/issues).
  - type: textarea
    id: issue-description
    attributes:
      label: Describe the bug
      description: A concise description of the issue you're experiencing. **Example:** "safeExecute does not return the error when a function throws."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step list of how to reproduce the bug. **Example:** "1. Import safeExecute. 2. Call it with a function that throws an error."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen. **Example:** "I expected safeExecute to catch the error and return it as part of the result object."
    validations:
      required: true
  - type: textarea
    id: screenshots-or-videos
    attributes:
      label: Screenshots/Videos
      description: |
        If applicable, add screenshots or videos to help explain your problem.

        **Tip:** You can attach images or log files by dragging files into this area.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment (Node.js version, OS, etc.).
      placeholder: "Node.js 18, Windows 11"
    validations:
      required: false
  - type: input
    id: safe-execute-version
    attributes:
      label: Which version of Safe Execute are you using?
      description: You can obtain this from your package.json.
      placeholder: "1.0.0"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or details about the bug here.
    validations:
      required: false
